In [52]:
import numpy as np

# Define matrix A
A = np.array([[1, 1, 1, 1],
              [2, -1, 3, 4],
              [-3, 2, -2, 5],
              [1, -1, 4, -1]])

# Define matrix b
b = np.array([10, 8, -3, 5])

# Solve the matrix thru linear algebra 
solution = np.linalg.solve(A, b)

# Print the solution
print("The solution is:")
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")
print(f"z = {solution[2]}")
print(f"w = {solution[3]}")

The solution is:
x = 3.443396226415094
y = 4.69811320754717
z = 1.6226415094339623
w = 0.2358490566037736


In [53]:
import numpy as np

# Resistors
A = np.array([[1500 + 600, -600], [-600, 900 + 600]])
# DC Source
b = np.array([12, 15])

# Calculate the currents
c = np.linalg.solve(A, b)

# Assign currents with adjusted signs
I1 = c[0]
I3 = c[1]
I2 = I1-I3

# Print the currents
print(f"I1 = {I1 * 1000:.2f} mA")
print(f"I2 = {I2 * 1000:.2f} mA")
print(f"I3 = {I3 * 1000:.2f} mA")

I1 = 9.68 mA
I2 = -4.19 mA
I3 = 13.87 mA


In [54]:
import numpy as np

# Define matrix A
A = np.array([[2, 1, 3], 
              [1, 2, 1], 
              [3, 1, 2]])

# Calculate the inverse of the matrix A using linear algebra
A_inv = np.linalg.inv(A)

# Print the inverse
print(A_inv)

[[-0.375 -0.125  0.625]
 [-0.125  0.625 -0.125]
 [ 0.625 -0.125 -0.375]]
